name: plot
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  
  - pip
    pip:
      - pandas
      - matplotlib
      - h5py
      - pyproj
      - folium
      - requests
      - streamlit-folium
 
  

