name: plot
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - pandas
  - pathlib
  - streamlit
  - h5py
  - conda-forge::pyproj
  - conda-forge::folium
  - conda-forge::streamlit-folium
  - xlrd
  - openpyxl
  - seaborn
  - scipy
  - statsmodels
  - pmdarima
  - matplotlib

