[theme]
primaryColor="#f8f8ff"
backgroundColor="#f8f8ff"
secondaryBackgroundColor="#dcdcdc"
textColor="#000000"
baseFontSize=16


font = 'sans-serif'

[theme.sidebar]

primaryColor="#000000"
backgroundColor="#dcdcdc"
textColor="#000000"